//!
//! AUTO-GENERATED CODE - DO NOT EDIT!
//!
//! Event Stream API
//! Source: crates/oas3-gen/fixtures/event_stream.json
//! Version: 1.0.0
//! Generated by `oas3-gen v0.23.6`
//!
//! API with Server-Sent Events (SSE) endpoint

use anyhow::Context;
#[allow(unused_imports)]
use reqwest::header::HeaderValue;
#[allow(unused_imports)]
use reqwest::multipart::{Form, Part};
use reqwest::{Client, Url};
use validator::Validate;

use super::types::*;
pub const BASE_URL: &str = "https://api.example.com";
#[derive(Debug, Clone)]
pub struct EventStreamApiClient {
  pub client: Client,
  pub base_url: Url,
}
impl EventStreamApiClient {
  /// Create a client using the OpenAPI `servers[0]` URL.
  #[must_use]
  pub fn new() -> Self {
    Self {
      client: Client::builder().build().expect("client"),
      base_url: Url::parse(BASE_URL).expect("valid base url"),
    }
  }
  /// Create a client with a custom base URL.
  pub fn with_base_url(base_url: impl AsRef<str>) -> anyhow::Result<Self> {
    Ok(Self {
      client: Client::builder().build().context("building reqwest client")?,
      base_url: Url::parse(base_url.as_ref()).context("parsing base url")?,
    })
  }
  /// Create a client from an existing `reqwest::Client`.
  pub fn with_client(base_url: impl AsRef<str>, client: Client) -> anyhow::Result<Self> {
    let url = Url::parse(base_url.as_ref()).context("parsing base url")?;
    Ok(Self { client, base_url: url })
  }
  ///Stream events
  ///
  ///Returns a stream of server-sent events
  ///
  ///GET /events
  pub async fn stream_events(&self, request: StreamEventsRequest) -> anyhow::Result<StreamEventsResponse> {
    request.validate().context("parameter validation")?;
    let mut url = self.base_url.clone();
    url
      .path_segments_mut()
      .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
      .push("events");
    let response = self.client.get(url).send().await?;
    StreamEventsRequest::parse_response(response).await
  }
  ///Stream typed events
  ///
  ///Returns a stream of typed server-sent events with query parameters
  ///
  ///GET /events/typed
  pub async fn stream_typed_events(
    &self,
    request: StreamTypedEventsRequest,
  ) -> anyhow::Result<StreamTypedEventsResponse> {
    request.validate().context("parameter validation")?;
    let mut url = self.base_url.clone();
    url
      .path_segments_mut()
      .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
      .push("events")
      .push("typed");
    let response = self.client.get(url).query(&request.query).send().await?;
    StreamTypedEventsRequest::parse_response(response).await
  }
}
