//!
//! AUTO-GENERATED CODE - DO NOT EDIT!
//!
//! Event Stream API
//! Source: crates/oas3-gen/fixtures/event_stream.json
//! Version: 1.0.0
//! Generated by `oas3-gen v0.23.6`
//!
//! API with Server-Sent Events (SSE) endpoint

use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, PartialEq, Deserialize, oas3_gen_support::Default)]
pub struct EventPayload {
  pub id: String,
  pub name: Option<String>,
  pub value: Option<i64>,
}
#[derive(Debug, Clone, PartialEq, Deserialize, oas3_gen_support::Default)]
pub struct StreamEvent {
  ///Event data payload
  pub data: String,
  ///Unique event identifier
  pub id: String,
  ///Event timestamp
  pub timestamp: Option<chrono::DateTime<chrono::Utc>>,
}
///Returns a stream of server-sent events
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub struct StreamEventsRequest {}
impl StreamEventsRequest {
  ///Parse the HTTP response into the response enum.
  pub async fn parse_response(req: reqwest::Response) -> anyhow::Result<StreamEventsResponse> {
    let status = req.status();
    if status.is_success() {
      let data = <oas3_gen_support::EventStream<StreamEvent>>::from_response(req);
      return Ok(StreamEventsResponse::Ok(data));
    }
    let _ = req.bytes().await?;
    Ok(StreamEventsResponse::Unknown)
  }
}
///Response types for streamEvents
#[derive(Debug)]
pub enum StreamEventsResponse {
  ///200: A stream of events
  Ok(oas3_gen_support::EventStream<StreamEvent>),
  ///default: Unknown response
  Unknown,
}
///Returns a stream of typed server-sent events with query parameters
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub struct StreamTypedEventsRequest {
  pub query: StreamTypedEventsRequestQuery,
}
impl StreamTypedEventsRequest {
  ///Parse the HTTP response into the response enum.
  pub async fn parse_response(req: reqwest::Response) -> anyhow::Result<StreamTypedEventsResponse> {
    let status = req.status();
    if status.is_success() {
      let data = <oas3_gen_support::EventStream<TypedEvent>>::from_response(req);
      return Ok(StreamTypedEventsResponse::Ok(data));
    }
    let _ = req.bytes().await?;
    Ok(StreamTypedEventsResponse::Unknown)
  }
}
#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, PartialEq, Serialize, oas3_gen_support::Default)]
pub struct StreamTypedEventsRequestQuery {
  pub filter: Option<String>,
}
///Response types for streamTypedEvents
#[derive(Debug)]
pub enum StreamTypedEventsResponse {
  ///200: A stream of typed events
  Ok(oas3_gen_support::EventStream<TypedEvent>),
  ///default: Unknown response
  Unknown,
}
#[derive(Debug, Clone, PartialEq, Deserialize, oas3_gen_support::Default)]
pub struct TypedEvent {
  pub payload: EventPayload,
  ///Event type
  #[serde(rename = "type")]
  pub r#type: TypedEventType,
}
///Event type
#[derive(Debug, Clone, PartialEq, Eq, Hash, Deserialize, oas3_gen_support::Default)]
pub enum TypedEventType {
  #[serde(rename = "created")]
  #[default]
  Created,
  #[serde(rename = "updated")]
  Updated,
  #[serde(rename = "deleted")]
  Deleted,
}
