//!
//! AUTO-GENERATED CODE - DO NOT EDIT!
//!
//! Strict Discriminated Union API
//! Source: crates/oas3-gen/fixtures/strict_union.json
//! Version: 1.0.0
//! Generated by `oas3-gen v0.26.1`
//!
//! Discriminated unions whose variants assert additionalProperties:false (so the generated variant structs carry deny_unknown_fields). The Change and Filter unions are used in both the request and the response, so each gets both a custom Serialize and a custom Deserialize impl. Exercises that the discriminator field round-trips through serde even though the variant struct rejects unknown fields and skips deserializing its own discriminator.

use anyhow::Context;
use reqwest::{Client, Url};
use validator::Validate;

use super::types::*;
pub const BASE_URL: &str = "https://example.com/";
#[derive(Debug, Clone)]
pub struct StrictDiscriminatedUnionApiClient {
  pub client: Client,
  pub base_url: Url,
}
impl Default for StrictDiscriminatedUnionApiClient {
  fn default() -> Self {
    Self::new()
  }
}
impl StrictDiscriminatedUnionApiClient {
  /// Create a client using the OpenAPI `servers[0]` URL.
  #[must_use]
  #[track_caller]
  pub fn new() -> Self {
    Self {
      client: Client::builder().build().expect("client"),
      base_url: Url::parse(BASE_URL).expect("valid base url"),
    }
  }
  /// Create a client with a custom base URL.
  pub fn with_base_url(base_url: impl AsRef<str>) -> anyhow::Result<Self> {
    Ok(Self {
      client: Client::builder().build().context("building reqwest client")?,
      base_url: Url::parse(base_url.as_ref()).context("parsing base url")?,
    })
  }
  /// Create a client from an existing `reqwest::Client`.
  pub fn with_client(base_url: impl AsRef<str>, client: Client) -> anyhow::Result<Self> {
    let url = Url::parse(base_url.as_ref()).context("parsing base url")?;
    Ok(Self { client, base_url: url })
  }
  /// Echo a change back
  ///
  /// * Path: `POST /echo`
  pub async fn echo_change(&self, request: EchoChangeRequest) -> anyhow::Result<EchoChangeResponse> {
    request.validate().context("parameter validation")?;
    let mut url = self.base_url.clone();
    url
      .path_segments_mut()
      .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
      .push("echo");
    let response = self.client.post(url).json(&request.body).send().await?;
    Ok(EchoChangeRequest::parse_response(response).await?)
  }
}
