#![allow(clippy::default_trait_access)]
#![allow(clippy::doc_markdown)]
#![allow(clippy::enum_variant_names)]
#![allow(clippy::large_enum_variant)]
#![allow(clippy::missing_panics_doc)]
#![allow(clippy::result_large_err)]
#![allow(clippy::struct_field_names)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::unnecessary_wraps)]
#![allow(clippy::unused_self)]
#![allow(dead_code)]
//!
//! AUTO-GENERATED CODE - DO NOT EDIT!
//!
//! Strict Discriminated Union API
//! Source: crates/oas3-gen/fixtures/strict_union.json
//! Version: 1.0.0
//! Generated by `oas3-gen v0.26.1`
//!
//! Discriminated unions whose variants assert additionalProperties:false (so the generated variant structs carry deny_unknown_fields). The Change and Filter unions are used in both the request and the response, so each gets both a custom Serialize and a custom Deserialize impl. Exercises that the discriminator field round-trips through serde even though the variant struct rejects unknown fields and skips deserializing its own discriminator.

mod client;
mod types;
pub use client::*;
pub use types::*;
