//!
//! AUTO-GENERATED CODE - DO NOT EDIT!
//!
//! Strict Discriminated Union API
//! Source: crates/oas3-gen/fixtures/strict_union.json
//! Version: 1.0.0
//! Generated by `oas3-gen v0.26.1`
//!
//! Discriminated unions whose variants assert additionalProperties:false (so the generated variant structs carry deny_unknown_fields). The Change and Filter unions are used in both the request and the response, so each gets both a custom Serialize and a custom Deserialize impl. Exercises that the discriminator field round-trips through serde even though the variant struct rejects unknown fields and skips deserializing its own discriminator.

use serde::{Deserialize, Serialize};
use validator::Validate;
#[derive(
  Debug, Clone, PartialEq, Serialize, Deserialize, validator::Validate, oas3_gen_support::Default, bon::Builder,
)]
pub struct ChangeMetadata {
  #[validate(length(min = 1u64))]
  pub uuid: String,
  #[serde(rename = "deviceId")]
  #[validate(length(min = 1u64))]
  pub device_id: String,
}
#[derive(Debug, Clone, PartialEq)]
pub enum Change {
  MediaItem(MediaItemChange),
  Playlist(PlaylistChange),
}
impl Change {
  pub const DISCRIMINATOR_FIELD: &'static str = "type";
}
impl Default for Change {
  fn default() -> Self {
    Self::MediaItem(<MediaItemChange>::default())
  }
}
impl serde::Serialize for Change {
  fn serialize<S>(&self, serializer: S) -> core::result::Result<S::Ok, S::Error>
  where
    S: serde::Serializer,
  {
    match self {
      Self::MediaItem(v) => v.serialize(serializer),
      Self::Playlist(v) => v.serialize(serializer),
    }
  }
}
impl<'de> serde::Deserialize<'de> for Change {
  fn deserialize<D>(deserializer: D) -> core::result::Result<Self, D::Error>
  where
    D: serde::Deserializer<'de>,
  {
    let mut value = serde_json::Value::deserialize(deserializer)?;
    let discriminator = value
      .as_object_mut()
      .and_then(|map| map.remove(Self::DISCRIMINATOR_FIELD))
      .and_then(|disc| disc.as_str().map(str::to_owned));
    match discriminator.as_deref() {
      Some("mediaItem") => serde_json::from_value(value)
        .map(Self::MediaItem)
        .map_err(serde::de::Error::custom),
      Some("playlist") => serde_json::from_value(value)
        .map(Self::Playlist)
        .map_err(serde::de::Error::custom),
      None => Err(serde::de::Error::missing_field(Self::DISCRIMINATOR_FIELD)),
      Some(other) => Err(serde::de::Error::custom(format!(
        "Unknown discriminator value '{}' for field '{}'",
        other, "type"
      ))),
    }
  }
}
#[serde_with::skip_serializing_none]
#[derive(
  Debug, Clone, PartialEq, Serialize, Deserialize, validator::Validate, oas3_gen_support::Default, bon::Builder,
)]
#[serde(deny_unknown_fields, default)]
pub struct MediaItemChange {
  #[validate(length(min = 1u64))]
  pub uuid: String,
  #[serde(rename = "deviceId")]
  #[validate(length(min = 1u64))]
  pub device_id: String,
  #[doc(hidden)]
  #[serde(default, rename = "type", skip_deserializing)]
  #[default(Some("mediaItem"))]
  #[builder(skip = Some("mediaItem"))]
  pub r#type: Option<&'static str>,
  pub title: Option<String>,
  pub filter: Option<Box<Filter>>,
}
#[serde_with::skip_serializing_none]
#[derive(
  Debug, Clone, PartialEq, Serialize, Deserialize, validator::Validate, oas3_gen_support::Default, bon::Builder,
)]
#[serde(deny_unknown_fields, default)]
pub struct PlaylistChange {
  #[validate(length(min = 1u64))]
  pub uuid: String,
  #[serde(rename = "deviceId")]
  #[validate(length(min = 1u64))]
  pub device_id: String,
  #[doc(hidden)]
  #[serde(default, rename = "type", skip_deserializing)]
  #[default(Some("playlist"))]
  #[builder(skip = Some("playlist"))]
  pub r#type: Option<&'static str>,
  pub name: Option<String>,
}
#[derive(Debug, Clone, PartialEq)]
pub enum Filter {
  String(StringFilter),
  Number(NumberFilter),
}
impl Filter {
  pub const DISCRIMINATOR_FIELD: &'static str = "type";
}
impl Default for Filter {
  fn default() -> Self {
    Self::String(<StringFilter>::default())
  }
}
impl serde::Serialize for Filter {
  fn serialize<S>(&self, serializer: S) -> core::result::Result<S::Ok, S::Error>
  where
    S: serde::Serializer,
  {
    match self {
      Self::String(v) => v.serialize(serializer),
      Self::Number(v) => v.serialize(serializer),
    }
  }
}
impl<'de> serde::Deserialize<'de> for Filter {
  fn deserialize<D>(deserializer: D) -> core::result::Result<Self, D::Error>
  where
    D: serde::Deserializer<'de>,
  {
    let mut value = serde_json::Value::deserialize(deserializer)?;
    let discriminator = value
      .as_object_mut()
      .and_then(|map| map.remove(Self::DISCRIMINATOR_FIELD))
      .and_then(|disc| disc.as_str().map(str::to_owned));
    match discriminator.as_deref() {
      Some("string") => serde_json::from_value(value)
        .map(Self::String)
        .map_err(serde::de::Error::custom),
      Some("number") => serde_json::from_value(value)
        .map(Self::Number)
        .map_err(serde::de::Error::custom),
      None => Err(serde::de::Error::missing_field(Self::DISCRIMINATOR_FIELD)),
      Some(other) => Err(serde::de::Error::custom(format!(
        "Unknown discriminator value '{}' for field '{}'",
        other, "type"
      ))),
    }
  }
}
impl Filter {
  pub fn string(value: String) -> Self {
    Self::String(StringFilter {
      value,
      ..Default::default()
    })
  }
  pub fn number(value: f64) -> Self {
    Self::Number(NumberFilter {
      value,
      ..Default::default()
    })
  }
}
#[serde_with::skip_serializing_none]
#[derive(
  Debug, Clone, PartialEq, Serialize, Deserialize, validator::Validate, oas3_gen_support::Default, bon::Builder,
)]
#[serde(deny_unknown_fields, default)]
pub struct StringFilter {
  #[doc(hidden)]
  #[serde(default, rename = "type", skip_deserializing)]
  #[default(Some("string"))]
  #[builder(skip = Some("string"))]
  pub r#type: Option<&'static str>,
  #[validate(length(min = 1u64))]
  pub value: String,
}
#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default, bon::Builder)]
#[serde(deny_unknown_fields, default)]
pub struct NumberFilter {
  #[doc(hidden)]
  #[serde(default, rename = "type", skip_deserializing)]
  #[default(Some("number"))]
  #[builder(skip = Some("number"))]
  pub r#type: Option<&'static str>,
  pub value: f64,
}
/// Echo a change back
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub struct EchoChangeRequest {
  pub body: Change,
}
#[bon::bon]
impl EchoChangeRequest {
  /// Create a new request with the given parameters.
  #[builder]
  pub fn new(body: Change) -> anyhow::Result<Self> {
    let request = Self { body };
    request.validate()?;
    Ok(request)
  }
}
impl EchoChangeRequest {
  /// Parse the HTTP response into the response enum.
  pub async fn parse_response(req: reqwest::Response) -> anyhow::Result<EchoChangeResponse> {
    let status = req.status();
    if status == http::StatusCode::OK {
      let data = oas3_gen_support::Diagnostics::<Change>::json_with_diagnostics(req).await?;
      return Ok(EchoChangeResponse::Ok(data));
    }
    let _ = req.bytes().await?;
    return Ok(EchoChangeResponse::Unknown);
  }
}
/// Response types for echoChange
#[derive(Debug, Clone)]
pub enum EchoChangeResponse {
  ///200: The same change, echoed
  Ok(Change),
  ///default: Unknown response
  Unknown,
}
