#![allow(clippy::doc_markdown)]
#![allow(clippy::enum_variant_names)]
#![allow(clippy::large_enum_variant)]
#![allow(clippy::missing_panics_doc)]
#![allow(clippy::result_large_err)]
#![allow(clippy::unnecessary_wraps)]
#![allow(clippy::unused_self)]
//!
//! AUTO-GENERATED CODE - DO NOT EDIT!
//!
//! Swagger Petstore
//! Source: crates/oas3-gen/fixtures/petstore.json
//! Version: 1.0.0
//! Generated by `oas3-gen v0.21.1`
//!
//! No description provided

use serde::Deserialize;
///Create a pet
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub struct CreatePetsRequest {}
impl CreatePetsRequest {
    ///Render the request path with parameters.
    pub fn render_path(&self) -> anyhow::Result<String> {
        Ok("pets".to_string())
    }
    ///Parse the HTTP response into the response enum.
    pub async fn parse_response(
        req: reqwest::Response,
    ) -> anyhow::Result<CreatePetsResponse> {
        let status = req.status();
        if status.is_success() {
            let _ = req.bytes().await?;
            return Ok(CreatePetsResponse::Created);
        }
        let data = oas3_gen_support::Diagnostics::<Error>::json_with_diagnostics(req)
            .await?;
        Ok(CreatePetsResponse::Unknown(data))
    }
}
///Response types for createPets
#[derive(Debug, Clone)]
pub enum CreatePetsResponse {
    ///201: Null response
    Created,
    ///default: unexpected error
    Unknown(Error),
}
#[derive(Debug, Clone, PartialEq, Deserialize, oas3_gen_support::Default)]
pub struct Error {
    pub code: i32,
    pub message: String,
}
///List all pets
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub struct ListPetsRequest {
    ///How many items to return at one time (max 100)
    ///- Location: `Query`
    pub limit: Option<i32>,
}
impl ListPetsRequest {
    ///Render the request path with parameters.
    pub fn render_path(&self) -> anyhow::Result<String> {
        use std::fmt::Write as _;
        let mut path = "pets".to_string();
        let mut prefix = '\0';
        if let Some(value) = &self.limit {
            prefix = if prefix == '\0' { '?' } else { '&' };
            write!(
                & mut path, "{prefix}limit={}",
                oas3_gen_support::percent_encode_query_component(&
                oas3_gen_support::serialize_query_param(value) ?)
            )
                .unwrap();
        }
        Ok(path)
    }
    ///Parse the HTTP response into the response enum.
    pub async fn parse_response(
        req: reqwest::Response,
    ) -> anyhow::Result<ListPetsResponse> {
        let status = req.status();
        if status.is_success() {
            let data = oas3_gen_support::Diagnostics::<Pets>::json_with_diagnostics(req)
                .await?;
            return Ok(ListPetsResponse::Ok(data));
        }
        let data = oas3_gen_support::Diagnostics::<Error>::json_with_diagnostics(req)
            .await?;
        Ok(ListPetsResponse::Unknown(data))
    }
}
///Response types for listPets
#[derive(Debug, Clone)]
pub enum ListPetsResponse {
    ///200: A paged array of pets
    Ok(Pets),
    ///default: unexpected error
    Unknown(Error),
}
#[derive(Debug, Clone, PartialEq, Deserialize, oas3_gen_support::Default)]
pub struct Pet {
    pub id: i64,
    pub name: String,
    pub tag: Option<String>,
}
pub type Pets = Vec<Pet>;
///Info for a specific pet
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub struct ShowPetByIdRequest {
    ///The id of the pet to retrieve
    ///- Location: `Path`
    #[validate(length(min = 1u64))]
    pub pet_id: String,
}
impl ShowPetByIdRequest {
    ///Render the request path with parameters.
    pub fn render_path(&self) -> anyhow::Result<String> {
        Ok(
            format!(
                "pets/{}", oas3_gen_support::percent_encode_path_segment(&
                oas3_gen_support::serialize_query_param(& self.pet_id) ?)
            ),
        )
    }
    ///Parse the HTTP response into the response enum.
    pub async fn parse_response(
        req: reqwest::Response,
    ) -> anyhow::Result<ShowPetByIdResponse> {
        let status = req.status();
        if status.is_success() {
            let data = oas3_gen_support::Diagnostics::<Pet>::json_with_diagnostics(req)
                .await?;
            return Ok(ShowPetByIdResponse::Ok(data));
        }
        let data = oas3_gen_support::Diagnostics::<Error>::json_with_diagnostics(req)
            .await?;
        Ok(ShowPetByIdResponse::Unknown(data))
    }
}
///Response types for showPetById
#[derive(Debug, Clone)]
pub enum ShowPetByIdResponse {
    ///200: Expected response to a valid request
    Ok(Pet),
    ///default: unexpected error
    Unknown(Error),
}

