//!
//! AUTO-GENERATED CODE - DO NOT EDIT!
//!
//! Swagger Petstore
//! Source: crates/oas3-gen/fixtures/petstore.json
//! Version: 1.0.0
//! Generated by `oas3-gen v0.23.4`
//!
//! No description provided

use serde::{Deserialize, Serialize};
use validator::Validate;
///Create a pet
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub struct CreatePetsRequest {}
impl CreatePetsRequest {
  ///Parse the HTTP response into the response enum.
  pub async fn parse_response(req: reqwest::Response) -> anyhow::Result<CreatePetsResponse> {
    let status = req.status();
    if status.is_success() {
      let _ = req.bytes().await?;
      return Ok(CreatePetsResponse::Created);
    }
    let data = oas3_gen_support::Diagnostics::<Error>::json_with_diagnostics(req).await?;
    Ok(CreatePetsResponse::Unknown(data))
  }
}
///Response types for createPets
#[derive(Debug, Clone)]
pub enum CreatePetsResponse {
  ///201: Null response
  Created,
  ///default: unexpected error
  Unknown(Error),
}
#[derive(Debug, Clone, PartialEq, Deserialize, oas3_gen_support::Default)]
pub struct Error {
  pub code: i32,
  pub message: String,
}
///List all pets
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub struct ListPetsRequest {
  #[validate(nested)]
  pub query: ListPetsRequestQuery,
}
impl ListPetsRequest {
  ///Parse the HTTP response into the response enum.
  pub async fn parse_response(req: reqwest::Response) -> anyhow::Result<ListPetsResponse> {
    let status = req.status();
    if status.is_success() {
      let data = oas3_gen_support::Diagnostics::<Pets>::json_with_diagnostics(req).await?;
      return Ok(ListPetsResponse::Ok(data));
    }
    let data = oas3_gen_support::Diagnostics::<Error>::json_with_diagnostics(req).await?;
    Ok(ListPetsResponse::Unknown(data))
  }
}
#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, PartialEq, Serialize, validator::Validate, oas3_gen_support::Default)]
pub struct ListPetsRequestQuery {
  ///How many items to return at one time (max 100)
  #[validate(range(min = 1i32, max = 100i32))]
  pub limit: Option<i32>,
}
///Response types for listPets
#[derive(Debug, Clone)]
pub enum ListPetsResponse {
  ///200: A paged array of pets
  Ok(Pets),
  ///default: unexpected error
  Unknown(Error),
}
#[derive(Debug, Clone, PartialEq, Deserialize, oas3_gen_support::Default)]
pub struct Pet {
  pub id: i64,
  pub name: String,
  pub tag: Option<String>,
}
pub type Pets = Vec<Pet>;
///Info for a specific pet
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub struct ShowPetByIdRequest {
  #[validate(nested)]
  pub path: ShowPetByIdRequestPath,
}
impl ShowPetByIdRequest {
  ///Parse the HTTP response into the response enum.
  pub async fn parse_response(req: reqwest::Response) -> anyhow::Result<ShowPetByIdResponse> {
    let status = req.status();
    if status.is_success() {
      let data = oas3_gen_support::Diagnostics::<Pet>::json_with_diagnostics(req).await?;
      return Ok(ShowPetByIdResponse::Ok(data));
    }
    let data = oas3_gen_support::Diagnostics::<Error>::json_with_diagnostics(req).await?;
    Ok(ShowPetByIdResponse::Unknown(data))
  }
}
#[derive(Debug, Clone, PartialEq, validator::Validate, oas3_gen_support::Default)]
pub struct ShowPetByIdRequestPath {
  ///The id of the pet to retrieve
  #[validate(length(min = 1u64))]
  pub pet_id: String,
}
///Response types for showPetById
#[derive(Debug, Clone)]
pub enum ShowPetByIdResponse {
  ///200: Expected response to a valid request
  Ok(Pet),
  ///default: unexpected error
  Unknown(Error),
}
