//!
//! AUTO-GENERATED CODE - DO NOT EDIT!
//!
//! Swagger Petstore
//! Source: crates/oas3-gen/fixtures/petstore.json
//! Version: 1.0.0
//! Generated by `oas3-gen v0.25.0`
//!

use super::types::*;
pub trait ApiServer {
  /// List all cats
  ///
  /// * Path: `GET /cats`
  async fn list_cats(&self, request: ListCatsRequest) -> anyhow::Result<ListCatsResponse>;
  /// List all pets
  ///
  /// * Path: `GET /pets`
  async fn list_pets(&self, request: ListPetsRequest) -> anyhow::Result<ListPetsResponse>;
  /// Create a pet
  ///
  /// * Path: `POST /pets`
  async fn create_pets(&self, request: CreatePetsRequest) -> anyhow::Result<CreatePetsResponse>;
  /// Info for a specific pet
  ///
  /// * Path: `GET /pets/{petId}`
  async fn show_pet_by_id(&self, request: ShowPetByIdRequest) -> anyhow::Result<ShowPetByIdResponse>;
  /// Upload pet image and update name
  ///
  /// * Path: `POST /pets/{petId}/upload`
  async fn upload_pet_image(&self, request: UploadPetImageRequest) -> anyhow::Result<ShowPetByIdResponse>;
}
