#![allow(clippy::doc_markdown)]
#![allow(clippy::enum_variant_names)]
#![allow(clippy::large_enum_variant)]
#![allow(clippy::missing_panics_doc)]
#![allow(clippy::result_large_err)]
#![allow(clippy::unnecessary_wraps)]
#![allow(clippy::unused_self)]
//!
//! AUTO-GENERATED CODE - DO NOT EDIT!
//!
//! Burger Shop
//! Source: crates/oas3-gen/fixtures/all-the-components.json
//! Version: 1.2
//! Generated by `oas3-gen v0.22.0`
//!
//! The best burger API at quobix. You can find the testiest burgers on the world
//!

use anyhow::Context;
#[allow(unused_imports)]
use reqwest::header::HeaderValue;
#[allow(unused_imports)]
use reqwest::multipart::{Form, Part};
use reqwest::{Client, Url};
use validator::Validate;

use super::*;
pub const BASE_URL: &str = "https://quobix.com/api";
#[derive(Debug, Clone)]
pub struct BurgerShopClient {
  pub client: Client,
  pub base_url: Url,
}
impl BurgerShopClient {
  /// Create a client using the OpenAPI `servers[0]` URL.
  #[must_use]
  pub fn new() -> Self {
    Self {
      client: Client::builder().build().expect("client"),
      base_url: Url::parse(BASE_URL).expect("valid base url"),
    }
  }
  /// Create a client with a custom base URL.
  pub fn with_base_url(base_url: impl AsRef<str>) -> anyhow::Result<Self> {
    Ok(Self {
      client: Client::builder().build().context("building reqwest client")?,
      base_url: Url::parse(base_url.as_ref()).context("parsing base url")?,
    })
  }
  /// Create a client from an existing `reqwest::Client`.
  pub fn with_client(base_url: impl AsRef<str>, client: Client) -> anyhow::Result<Self> {
    let url = Url::parse(base_url.as_ref()).context("parsing base url")?;
    Ok(Self { client, base_url: url })
  }
  ///Create a new burger
  ///
  ///A new burger for our menu, yummy yum yum.
  ///
  ///POST /burgers
  pub async fn create_burger(&self, request: CreateBurgerRequest) -> anyhow::Result<CreateBurgerResponse> {
    request.validate().context("parameter validation")?;
    let url = self
      .base_url
      .join(&request.render_path()?)
      .context("constructing request url")?;
    let mut req_builder = self.client.post(url);
    if let Some(body) = request.body.as_ref() {
      req_builder = req_builder.json(body);
    }
    let response = req_builder.send().await?;
    let parsed = request.parse_response(response).await?;
    Ok(parsed)
  }
  ///Search a burger by ID - returns the burger with that identifier
  ///
  ///Look up a tasty burger take it and enjoy it
  ///
  ///GET /burgers/{burgerId}
  pub async fn locate_burger(&self, request: LocateBurgerRequest) -> anyhow::Result<LocateBurgerResponse> {
    request.validate().context("parameter validation")?;
    let url = self
      .base_url
      .join(&request.render_path()?)
      .context("constructing request url")?;
    let req_builder = self.client.get(url);
    let response = req_builder.send().await?;
    let parsed = request.parse_response(response).await?;
    Ok(parsed)
  }
  ///Get a list of all dressings available
  ///
  ///Same as the summary, look up a tasty burger, by its ID - the burger identifier
  ///
  ///GET /burgers/{burgerId}/dressings
  pub async fn list_burger_dressings(
    &self,
    request: ListBurgerDressingsRequest,
  ) -> anyhow::Result<ListBurgerDressingsResponse> {
    request.validate().context("parameter validation")?;
    let url = self
      .base_url
      .join(&request.render_path()?)
      .context("constructing request url")?;
    let req_builder = self.client.get(url);
    let response = req_builder.send().await?;
    let parsed = request.parse_response(response).await?;
    Ok(parsed)
  }
  ///Get all dressings available in our store
  ///
  ///Get all dressings and choose from them
  ///
  ///GET /dressings
  pub async fn get_all_dressings(&self, request: GetAllDressingsRequest) -> anyhow::Result<GetAllDressingsResponse> {
    request.validate().context("parameter validation")?;
    let url = self
      .base_url
      .join(&request.render_path()?)
      .context("constructing request url")?;
    let req_builder = self.client.get(url);
    let response = req_builder.send().await?;
    let parsed = request.parse_response(response).await?;
    Ok(parsed)
  }
  ///Get a specific dressing - you can choose the dressing from our menu
  ///
  ///Same as the summary, get a dressing, by its ID
  ///
  ///GET /dressings/{dressingId}
  pub async fn get_dressing(&self, request: GetDressingRequest) -> anyhow::Result<GetDressingResponse> {
    request.validate().context("parameter validation")?;
    let url = self
      .base_url
      .join(&request.render_path()?)
      .context("constructing request url")?;
    let req_builder = self.client.get(url);
    let response = req_builder.send().await?;
    let parsed = request.parse_response(response).await?;
    Ok(parsed)
  }
}
