//!
//! AUTO-GENERATED CODE - DO NOT EDIT!
//!
//! Key Vault
//! Source: crates/oas3-gen/fixtures/api_key_security.json
//! Version: 1.0.0
//! Generated by `oas3-gen v0.29.0`
//!
//! Exercises apiKey security schemes in headers, query strings, and cookies.

use anyhow::Context;
use reqwest::{Client, Url};
use validator::Validate;

use super::types::*;
pub const BASE_URL: &str = "https://vault.example.com/v1";
#[derive(Clone)]
pub struct KeyVaultClient {
  pub client: Client,
  pub base_url: Url,
  /// Cookie API keys, which `client` sends with every request to the host of `base_url`.
  pub cookies: std::sync::Arc<reqwest_cookie_store::CookieStoreMutex>,
  /// `ApiKeyAuth` API key, sent in the `X-Api-Key` header.
  pub api_key_auth: Option<secrecy::SecretString>,
  /// `QueryKey` API key, sent in the `api_key` query parameter.
  pub query_key: Option<secrecy::SecretString>,
}
impl core::fmt::Debug for KeyVaultClient {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    f.debug_struct("KeyVaultClient")
      .field("client", &self.client)
      .field("base_url", &self.base_url)
      .field("api_key_auth", &self.api_key_auth)
      .field("query_key", &self.query_key)
      .finish_non_exhaustive()
  }
}
impl Default for KeyVaultClient {
  fn default() -> Self {
    Self::new()
  }
}
impl KeyVaultClient {
  /// Create a client using the OpenAPI `servers[0]` URL.
  #[must_use]
  #[track_caller]
  pub fn new() -> Self {
    let cookies = std::sync::Arc::new(reqwest_cookie_store::CookieStoreMutex::default());
    Self {
      client: Client::builder()
        .cookie_provider(std::sync::Arc::clone(&cookies))
        .build()
        .expect("client"),
      base_url: Url::parse(BASE_URL).expect("valid base url"),
      cookies,
      api_key_auth: None,
      query_key: None,
    }
  }
  /// Create a client with a custom base URL.
  pub fn with_base_url(base_url: impl AsRef<str>) -> anyhow::Result<Self> {
    let cookies = std::sync::Arc::new(reqwest_cookie_store::CookieStoreMutex::default());
    Ok(Self {
      client: Client::builder()
        .cookie_provider(std::sync::Arc::clone(&cookies))
        .build()
        .context("building reqwest client")?,
      base_url: Url::parse(base_url.as_ref()).context("parsing base url")?,
      cookies,
      api_key_auth: None,
      query_key: None,
    })
  }
  /// Create a client from an existing `reqwest::Client`.
  ///
  /// Cookie API keys go into a new `cookies` store, which `client` doesn't read. To
  /// send them, rebuild `client` with `cookie_provider(Arc::clone(&cookies))`.
  pub fn with_client(base_url: impl AsRef<str>, client: Client) -> anyhow::Result<Self> {
    let url = Url::parse(base_url.as_ref()).context("parsing base url")?;
    Ok(Self {
      client,
      base_url: url,
      cookies: std::sync::Arc::default(),
      api_key_auth: None,
      query_key: None,
    })
  }
  /// Set the `ApiKeyAuth` API key, sent in the `X-Api-Key` header to operations that accept it.
  #[must_use]
  pub fn with_api_key_auth(mut self, api_key: impl Into<String>) -> Self {
    self.api_key_auth = Some(secrecy::SecretString::from(api_key.into()));
    self
  }
  /// Set the `QueryKey` API key, sent in the `api_key` query parameter to operations that accept it.
  #[must_use]
  pub fn with_query_key(mut self, api_key: impl Into<String>) -> Self {
    self.query_key = Some(secrecy::SecretString::from(api_key.into()));
    self
  }
  /// Set the `SessionCookie` API key, sent in the `session` cookie with every request to the host of `base_url`.
  ///
  /// The key goes into `cookies`, which clones of this client share.
  #[must_use]
  pub fn with_session_cookie(self, api_key: impl Into<String>) -> Self {
    let cookie = reqwest_cookie_store::RawCookie::new("session", api_key.into());
    let _ = self
      .cookies
      .lock()
      .unwrap_or_else(std::sync::PoisonError::into_inner)
      .insert_raw(&cookie, &self.base_url);
    self
  }
  /// List secrets with the global header key
  ///
  /// * Path: `GET /secrets`
  pub async fn list_secrets(
    &self,
    request: ListSecretsRequest,
  ) -> anyhow::Result<ApiResponse<Secret200Response, Error>> {
    request.validate().context("parameter validation")?;
    let mut url = self.base_url.clone();
    url
      .path_segments_mut()
      .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
      .push("secrets");
    let mut req_builder = self.client.get(url).query(&request.query);
    if let Some(api_key) = &self.api_key_auth {
      req_builder = req_builder.header(X_API_KEY, secrecy::ExposeSecret::expose_secret(api_key));
    }
    let response = req_builder.send().await?;
    ListSecretsRequest::parse_response(response).await
  }
  /// Create a secret with a query key or a session cookie
  ///
  /// * Path: `POST /secrets`
  pub async fn create_secret(&self, request: CreateSecretRequest) -> anyhow::Result<ApiResponse<Secret, Error>> {
    request.validate().context("parameter validation")?;
    let mut url = self.base_url.clone();
    url
      .path_segments_mut()
      .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
      .push("secrets");
    let mut req_builder = self.client.post(url).json(&request.body);
    if let Some(api_key) = &self.query_key {
      req_builder = req_builder.query(&[("api_key", secrecy::ExposeSecret::expose_secret(api_key))]);
    }
    let response = req_builder.send().await?;
    CreateSecretRequest::parse_response(response).await
  }
  /// Read a secret with both the header key and a session cookie
  ///
  /// * Path: `GET /secrets/{secretId}`
  pub async fn get_secret(&self, request: GetSecretRequest) -> anyhow::Result<ApiResponse<Secret, Error>> {
    request.validate().context("parameter validation")?;
    let mut url = self.base_url.clone();
    url
      .path_segments_mut()
      .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
      .push("secrets")
      .push(&request.path.secret_id.clone());
    let mut req_builder = self.client.get(url);
    if let Some(api_key) = &self.api_key_auth {
      req_builder = req_builder.header(X_API_KEY, secrecy::ExposeSecret::expose_secret(api_key));
    }
    let response = req_builder.send().await?;
    GetSecretRequest::parse_response(response).await
  }
  /// Delete a secret with a bearer token or the header key
  ///
  /// * Path: `DELETE /secrets/{secretId}`
  pub async fn delete_secret(&self, request: DeleteSecretRequest) -> anyhow::Result<ApiResponse<(), Error>> {
    request.validate().context("parameter validation")?;
    let mut url = self.base_url.clone();
    url
      .path_segments_mut()
      .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
      .push("secrets")
      .push(&request.path.secret_id.clone());
    let mut req_builder = self.client.delete(url);
    if let Some(api_key) = &self.api_key_auth {
      req_builder = req_builder.header(X_API_KEY, secrecy::ExposeSecret::expose_secret(api_key));
    }
    let response = req_builder.send().await?;
    DeleteSecretRequest::parse_response(response).await
  }
  /// Report health without credentials
  ///
  /// * Path: `GET /health`
  pub async fn get_health(&self, request: GetHealthRequest) -> anyhow::Result<ApiResponse<(), ()>> {
    request.validate().context("parameter validation")?;
    let mut url = self.base_url.clone();
    url
      .path_segments_mut()
      .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
      .push("health");
    let response = self.client.get(url).send().await?;
    GetHealthRequest::parse_response(response).await
  }
}
