//!
//! AUTO-GENERATED CODE - DO NOT EDIT!
//!
//! Key Vault
//! Source: crates/oas3-gen/fixtures/api_key_security.json
//! Version: 1.0.0
//! Generated by `oas3-gen v0.29.0`
//!
//! Exercises apiKey security schemes in headers, query strings, and cookies.

use serde::{Deserialize, Serialize};
use validator::Validate;
pub const X_API_KEY: http::HeaderName = http::HeaderName::from_static("x-api-key");
#[derive(Debug, Clone, PartialEq, Deserialize, oas3_gen_support::Default, bon::Builder)]
pub struct Secret {
  pub id: String,
  pub name: String,
}
#[derive(Debug, Clone, PartialEq, Serialize, validator::Validate, oas3_gen_support::Default, bon::Builder)]
pub struct NewSecret {
  #[validate(length(min = 1u64))]
  pub name: String,
  #[validate(length(min = 1u64))]
  pub value: String,
}
#[derive(Debug, Clone, PartialEq, Deserialize, oas3_gen_support::Default, bon::Builder)]
pub struct Error {
  pub code: String,
  pub message: String,
}
#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, PartialEq, Serialize, validator::Validate, oas3_gen_support::Default)]
pub struct ListSecretsRequestQuery {
  #[validate(range(min = 1i64))]
  pub limit: Option<i64>,
}
/// List secrets with the global header key
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub struct ListSecretsRequest {
  #[validate(nested)]
  pub query: ListSecretsRequestQuery,
}
#[bon::bon]
impl ListSecretsRequest {
  /// Create a new request with the given parameters.
  #[builder]
  pub fn new(limit: Option<i64>) -> anyhow::Result<Self> {
    let request = Self {
      query: ListSecretsRequestQuery { limit },
    };
    request.validate()?;
    Ok(request)
  }
}
impl ListSecretsRequest {
  /// Parse the HTTP response into the response enum.
  pub async fn parse_response(req: reqwest::Response) -> anyhow::Result<ApiResponse<Secret200Response, Error>> {
    let status = req.status();
    if status == http::StatusCode::OK {
      let data = oas3_gen_support::Diagnostics::<Secret200Response>::json_with_diagnostics(req).await?;
      return Ok(ApiResponse::Ok(data));
    }
    if status == http::StatusCode::UNAUTHORIZED {
      let data = oas3_gen_support::Diagnostics::<Error>::json_with_diagnostics(req).await?;
      return Ok(ApiResponse::Unauthorized(data));
    }
    Ok(ApiResponse::Other(status, req.bytes().await?.to_vec()))
  }
}
/// Create a secret with a query key or a session cookie
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub struct CreateSecretRequest {
  #[validate(nested)]
  pub body: NewSecret,
}
#[bon::bon]
impl CreateSecretRequest {
  /// Create a new request with the given parameters.
  #[builder]
  pub fn new(body: NewSecret) -> anyhow::Result<Self> {
    let request = Self { body };
    request.validate()?;
    Ok(request)
  }
}
impl CreateSecretRequest {
  /// Parse the HTTP response into the response enum.
  pub async fn parse_response(req: reqwest::Response) -> anyhow::Result<ApiResponse<Secret, Error>> {
    let status = req.status();
    if status == http::StatusCode::CREATED {
      let data = oas3_gen_support::Diagnostics::<Secret>::json_with_diagnostics(req).await?;
      return Ok(ApiResponse::Created(data));
    }
    if status == http::StatusCode::UNAUTHORIZED {
      let data = oas3_gen_support::Diagnostics::<Error>::json_with_diagnostics(req).await?;
      return Ok(ApiResponse::Unauthorized(data));
    }
    Ok(ApiResponse::Other(status, req.bytes().await?.to_vec()))
  }
}
#[derive(Debug, Clone, PartialEq, validator::Validate, oas3_gen_support::Default)]
pub struct GetSecretRequestPath {
  #[validate(length(min = 1u64))]
  pub secret_id: String,
}
/// Read a secret with both the header key and a session cookie
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub struct GetSecretRequest {
  #[validate(nested)]
  pub path: GetSecretRequestPath,
}
#[bon::bon]
impl GetSecretRequest {
  /// Create a new request with the given parameters.
  #[builder]
  pub fn new(secret_id: String) -> anyhow::Result<Self> {
    let request = Self {
      path: GetSecretRequestPath { secret_id },
    };
    request.validate()?;
    Ok(request)
  }
}
impl GetSecretRequest {
  /// Parse the HTTP response into the response enum.
  pub async fn parse_response(req: reqwest::Response) -> anyhow::Result<ApiResponse<Secret, Error>> {
    let status = req.status();
    if status == http::StatusCode::OK {
      let data = oas3_gen_support::Diagnostics::<Secret>::json_with_diagnostics(req).await?;
      return Ok(ApiResponse::Ok(data));
    }
    if status == http::StatusCode::UNAUTHORIZED {
      let data = oas3_gen_support::Diagnostics::<Error>::json_with_diagnostics(req).await?;
      return Ok(ApiResponse::Unauthorized(data));
    }
    Ok(ApiResponse::Other(status, req.bytes().await?.to_vec()))
  }
}
#[derive(Debug, Clone, PartialEq, validator::Validate, oas3_gen_support::Default)]
pub struct DeleteSecretRequestPath {
  #[validate(length(min = 1u64))]
  pub secret_id: String,
}
/// Delete a secret with a bearer token or the header key
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub struct DeleteSecretRequest {
  #[validate(nested)]
  pub path: DeleteSecretRequestPath,
}
#[bon::bon]
impl DeleteSecretRequest {
  /// Create a new request with the given parameters.
  #[builder]
  pub fn new(secret_id: String) -> anyhow::Result<Self> {
    let request = Self {
      path: DeleteSecretRequestPath { secret_id },
    };
    request.validate()?;
    Ok(request)
  }
}
impl DeleteSecretRequest {
  /// Parse the HTTP response into the response enum.
  pub async fn parse_response(req: reqwest::Response) -> anyhow::Result<ApiResponse<(), Error>> {
    let status = req.status();
    if status == http::StatusCode::NO_CONTENT {
      let _ = req.bytes().await?;
      return Ok(ApiResponse::NoContent);
    }
    if status == http::StatusCode::UNAUTHORIZED {
      let data = oas3_gen_support::Diagnostics::<Error>::json_with_diagnostics(req).await?;
      return Ok(ApiResponse::Unauthorized(data));
    }
    Ok(ApiResponse::Other(status, req.bytes().await?.to_vec()))
  }
}
/// Report health without credentials
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub struct GetHealthRequest {}
impl GetHealthRequest {
  /// Parse the HTTP response into the response enum.
  pub async fn parse_response(req: reqwest::Response) -> anyhow::Result<ApiResponse<(), ()>> {
    let status = req.status();
    if status == http::StatusCode::NO_CONTENT {
      let _ = req.bytes().await?;
      return Ok(ApiResponse::NoContent);
    }
    Ok(ApiResponse::Other(status, req.bytes().await?.to_vec()))
  }
}
pub type Secret200Response = Vec<Secret>;
/// Response enum shared by every operation.
///
/// `Value` is the operation's success body type and `Failure` its error body type.
/// A status code is a unit variant when no operation gives it a body.
#[derive(Debug, Clone)]
pub enum ApiResponse<Value, Failure> {
  ///200
  Ok(Value),
  ///201
  Created(Value),
  ///204
  NoContent,
  ///401
  Unauthorized(Failure),
  ///Status code the operation does not declare; carries the raw body.
  Other(http::StatusCode, Vec<u8>),
}
