#![allow(clippy::default_trait_access)]
#![allow(clippy::doc_markdown)]
#![allow(clippy::enum_variant_names)]
#![allow(clippy::large_enum_variant)]
#![allow(clippy::missing_errors_doc)]
#![allow(clippy::missing_panics_doc)]
#![allow(clippy::result_large_err)]
#![allow(clippy::struct_field_names)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::unnecessary_wraps)]
#![allow(clippy::unused_self)]
#![allow(dead_code)]
//!
//! AUTO-GENERATED CODE - DO NOT EDIT!
//!
//! Multipart Forms
//! Source: crates/oas3-gen/fixtures/multipart.json
//! Version: 1.0.0
//! Generated by `oas3-gen v0.29.0`
//!
//! Exercises multipart/form-data request bodies: file parts, Encoding Objects, and RFC 6570 styles

mod server;
mod types;
pub use server::*;
pub use types::*;
