//!
//! AUTO-GENERATED CODE - DO NOT EDIT!
//!
//! Multipart Forms
//! Source: crates/oas3-gen/fixtures/multipart.json
//! Version: 1.0.0
//! Generated by `oas3-gen v0.29.0`
//!
//! Exercises multipart/form-data request bodies: file parts, Encoding Objects, and RFC 6570 styles

use axum::{
  Router,
  extract::{Path, State},
  response::IntoResponse,
  routing::post,
};

use super::types::*;
pub trait ApiServer: Send + Sync {
  /// Submit a form that mixes files, scalars, and structured values
  ///
  /// * Path: `POST /forms/{formId}`
  fn submit_form(
    &self,
    request: SubmitFormRequest,
  ) -> impl std::future::Future<Output = anyhow::Result<ApiResponse<UploadForm>>> + Send;
  /// Upload any number of files under one part name
  ///
  /// * Path: `POST /files`
  fn upload_files(
    &self,
    request: UploadFilesRequest,
  ) -> impl std::future::Future<Output = anyhow::Result<ApiResponse<FilesReceipt>>> + Send;
  /// Submit free-form text fields
  ///
  /// * Path: `POST /metadata`
  fn submit_metadata(
    &self,
    request: SubmitMetadataRequest,
  ) -> impl std::future::Future<Output = anyhow::Result<ApiResponse<Metadata>>> + Send;
  /// Submit named lists of counts
  ///
  /// * Path: `POST /counters`
  fn submit_counters(
    &self,
    request: SubmitCountersRequest,
  ) -> impl std::future::Future<Output = anyhow::Result<ApiResponse<Counters>>> + Send;
}
pub async fn submit_form<S>(
  State(service): State<S>,
  Path(path): Path<SubmitFormRequestPath>,
  multipart: axum::extract::Multipart,
) -> impl IntoResponse
where
  S: ApiServer + Clone + Send + Sync + 'static,
{
  #[allow(clippy::similar_names)]
  async fn multipart_body(mut multipart: axum::extract::Multipart) -> anyhow::Result<UploadForm> {
    let mut fields = serde_json::Map::new();
    let mut file_parts = None;
    let mut attachments_parts = vec![];
    let mut thumbnail_parts = None;
    let mut tags_parts = vec![];
    let mut addresses_parts = vec![];
    let mut ids_parts = vec![];
    let mut colors_parts = vec![];
    let mut filter_parts = serde_json::Map::new();
    let mut range_parts = serde_json::Map::new();
    let mut extras_parts = serde_json::Map::new();
    let mut options_parts = serde_json::Map::new();
    while let Some(part) = multipart.next_field().await? {
      let Some(name) = part.name().map(str::to_owned) else {
        continue;
      };
      match name.as_str() {
        "name" => {
          fields.insert("name".to_owned(), serde_json::Value::String(part.text().await?));
        }
        "fileName" => {
          fields.insert("fileName".to_owned(), serde_json::Value::String(part.text().await?));
        }
        "type" => {
          fields.insert("type".to_owned(), serde_json::Value::String(part.text().await?));
        }
        "résumé" => {
          fields.insert("résumé".to_owned(), serde_json::Value::String(part.text().await?));
        }
        "file" => {
          file_parts = Some(Vec::from(part.bytes().await?));
        }
        "attachments" => {
          attachments_parts.push(Vec::from(part.bytes().await?));
        }
        "thumbnail" => {
          thumbnail_parts = Some(Vec::from(part.bytes().await?));
        }
        "encoded" => {
          fields.insert("encoded".to_owned(), serde_json::Value::String(part.text().await?));
        }
        "count" => {
          fields.insert(
            "count".to_owned(),
            serde_json::from_str(&part.text().await?)
              .map_err(|e| anyhow::anyhow!("invalid multipart part `{}`: {e}", "count"))?,
          );
        }
        "ratio" => {
          fields.insert(
            "ratio".to_owned(),
            serde_json::from_str(&part.text().await?)
              .map_err(|e| anyhow::anyhow!("invalid multipart part `{}`: {e}", "ratio"))?,
          );
        }
        "enabled" => {
          fields.insert(
            "enabled".to_owned(),
            serde_json::from_str(&part.text().await?)
              .map_err(|e| anyhow::anyhow!("invalid multipart part `{}`: {e}", "enabled"))?,
          );
        }
        "quality" => {
          fields.insert("quality".to_owned(), serde_json::Value::String(part.text().await?));
        }
        "level" => {
          fields.insert(
            "level".to_owned(),
            serde_json::from_str(&part.text().await?)
              .map_err(|e| anyhow::anyhow!("invalid multipart part `{}`: {e}", "level"))?,
          );
        }
        "tags" => {
          tags_parts.push(serde_json::Value::String(part.text().await?));
        }
        "createdAt" => {
          fields.insert("createdAt".to_owned(), serde_json::Value::String(part.text().await?));
        }
        "address" => {
          fields.insert(
            "address".to_owned(),
            serde_json::from_str(&part.text().await?)
              .map_err(|e| anyhow::anyhow!("invalid multipart part `{}`: {e}", "address"))?,
          );
        }
        "addresses" => {
          addresses_parts.push(
            serde_json::from_str(&part.text().await?)
              .map_err(|e| anyhow::anyhow!("invalid multipart part `{}`: {e}", "addresses"))?,
          );
        }
        "note" => {
          fields.insert("note".to_owned(), serde_json::Value::String(part.text().await?));
        }
        "labels" => {
          fields.insert("labels".to_owned(), {
            let is_json = part
              .content_type()
              .is_some_and(|content_type| content_type.contains("json"));
            let text = part.text().await?;
            if is_json {
              serde_json::from_str(&text).map_err(|e| anyhow::anyhow!("invalid multipart part `{}`: {e}", "labels"))?
            } else if serde_json::from_value::<UploadFormLabels>(serde_json::Value::String(text.clone())).is_ok() {
              serde_json::Value::String(text)
            } else {
              serde_json::from_str(&text).unwrap_or(serde_json::Value::String(text))
            }
          });
        }
        "ids" => {
          let text = part.text().await?;
          if !text.is_empty() {
            for item in text.split('|') {
              ids_parts.push(
                serde_json::from_str(item).map_err(|e| anyhow::anyhow!("invalid multipart part `{}`: {e}", "ids"))?,
              );
            }
          }
        }
        "colors" => {
          colors_parts.push(serde_json::Value::String(part.text().await?));
        }
        "range" => {
          let text = part.text().await?;
          let mut tokens = text.split(',');
          while let (Some(key), Some(member)) = (tokens.next(), tokens.next()) {
            let member = match key {
              "min" => serde_json::from_str(member)
                .map_err(|e| anyhow::anyhow!("invalid multipart part `{}`: {e}", "range"))?,
              "max" => serde_json::from_str(member)
                .map_err(|e| anyhow::anyhow!("invalid multipart part `{}`: {e}", "range"))?,
              _ => serde_json::Value::String(member.to_owned()),
            };
            range_parts.insert(key.to_owned(), member);
          }
        }
        _ => {
          if let Some(key) = name.strip_prefix("filter[").and_then(|key| key.strip_suffix(']')) {
            let member = match key {
              "size" => serde_json::from_str(&part.text().await?)
                .map_err(|e| anyhow::anyhow!("invalid multipart part `{}`: {e}", "filter"))?,
              _ => serde_json::Value::String(part.text().await?),
            };
            filter_parts.insert(key.to_owned(), member);
          } else if matches!(name.as_str(), "mood" | "score") {
            let member = match name.as_str() {
              "score" => serde_json::from_str(&part.text().await?)
                .map_err(|e| anyhow::anyhow!("invalid multipart part `{}`: {e}", "extras"))?,
              _ => serde_json::Value::String(part.text().await?),
            };
            extras_parts.insert(name, member);
          } else if let Some(key) = name.strip_prefix("options[").and_then(|key| key.strip_suffix(']')) {
            let member = serde_json::from_str(&part.text().await?)
              .map_err(|e| anyhow::anyhow!("invalid multipart part `{}`: {e}", "options"))?;
            options_parts.insert(key.to_owned(), member);
          }
        }
      }
    }
    fields.insert("attachments".to_owned(), serde_json::Value::Array(vec![]));
    fields.insert("thumbnail".to_owned(), serde_json::Value::Array(vec![]));
    if !tags_parts.is_empty() {
      fields.insert("tags".to_owned(), serde_json::Value::Array(tags_parts));
    }
    if !addresses_parts.is_empty() {
      fields.insert("addresses".to_owned(), serde_json::Value::Array(addresses_parts));
    }
    if !ids_parts.is_empty() {
      fields.insert("ids".to_owned(), serde_json::Value::Array(ids_parts));
    }
    if !colors_parts.is_empty() {
      fields.insert("colors".to_owned(), serde_json::Value::Array(colors_parts));
    }
    if !filter_parts.is_empty() {
      fields.insert("filter".to_owned(), serde_json::Value::Object(filter_parts));
    }
    if !range_parts.is_empty() {
      fields.insert("range".to_owned(), serde_json::Value::Object(range_parts));
    }
    if !extras_parts.is_empty() {
      fields.insert("extras".to_owned(), serde_json::Value::Object(extras_parts));
    }
    if !options_parts.is_empty() {
      fields.insert("options".to_owned(), serde_json::Value::Object(options_parts));
    }
    let mut body: UploadForm = serde_json::from_value(serde_json::Value::Object(fields))?;
    body.file = file_parts;
    body.attachments = attachments_parts;
    body.thumbnail = thumbnail_parts.ok_or_else(|| anyhow::anyhow!("missing multipart part `{}`", "thumbnail"))?;
    Ok(body)
  }
  let body = match multipart_body(multipart).await {
    Ok(body) => body,
    Err(e) => {
      return (axum::http::StatusCode::BAD_REQUEST, format!("Bad request: {e}")).into_response();
    }
  };
  let request = SubmitFormRequest { path, body };
  let result: anyhow::Result<ApiResponse<UploadForm>> = service.submit_form(request).await;
  match result {
    Ok(ApiResponse::Ok(body)) => (http::StatusCode::OK, axum::Json(body)).into_response(),
    Ok(ApiResponse::Other(status, body)) => (status, body).into_response(),
    Err(e) => (
      axum::http::StatusCode::INTERNAL_SERVER_ERROR,
      format!("Internal error: {e}"),
    )
      .into_response(),
  }
}
pub async fn upload_files<S>(State(service): State<S>, multipart: Option<axum::extract::Multipart>) -> impl IntoResponse
where
  S: ApiServer + Clone + Send + Sync + 'static,
{
  #[allow(clippy::similar_names)]
  async fn multipart_body(multipart: Option<axum::extract::Multipart>) -> anyhow::Result<Option<FileRequestBody>> {
    let Some(mut multipart) = multipart else {
      return Ok(None);
    };
    let mut fields = serde_json::Map::new();
    let mut file_parts = vec![];
    let mut cover_parts = None;
    while let Some(part) = multipart.next_field().await? {
      let Some(name) = part.name().map(str::to_owned) else {
        continue;
      };
      match name.as_str() {
        "file" => {
          file_parts.push(Vec::from(part.bytes().await?));
        }
        "cover" => {
          cover_parts = Some(Vec::from(part.bytes().await?));
        }
        "note" => {
          fields.insert("note".to_owned(), serde_json::Value::String(part.text().await?));
        }
        _ => {}
      }
    }
    let mut body: FileRequestBody = serde_json::from_value(serde_json::Value::Object(fields))?;
    body.file = (!file_parts.is_empty()).then_some(file_parts);
    body.cover = cover_parts;
    Ok(Some(body))
  }
  let body = match multipart_body(multipart).await {
    Ok(body) => body,
    Err(e) => {
      return (axum::http::StatusCode::BAD_REQUEST, format!("Bad request: {e}")).into_response();
    }
  };
  let request = UploadFilesRequest { body };
  let result: anyhow::Result<ApiResponse<FilesReceipt>> = service.upload_files(request).await;
  match result {
    Ok(ApiResponse::Ok(body)) => (http::StatusCode::OK, axum::Json(body)).into_response(),
    Ok(ApiResponse::Other(status, body)) => (status, body).into_response(),
    Err(e) => (
      axum::http::StatusCode::INTERNAL_SERVER_ERROR,
      format!("Internal error: {e}"),
    )
      .into_response(),
  }
}
pub async fn submit_metadata<S>(State(service): State<S>, multipart: axum::extract::Multipart) -> impl IntoResponse
where
  S: ApiServer + Clone + Send + Sync + 'static,
{
  async fn multipart_body(mut multipart: axum::extract::Multipart) -> anyhow::Result<Metadata> {
    let mut fields = serde_json::Map::new();
    while let Some(part) = multipart.next_field().await? {
      let Some(name) = part.name().map(str::to_owned) else {
        continue;
      };
      let value = serde_json::Value::String(part.text().await?);
      fields.insert(name, value);
    }
    let body: Metadata = serde_json::from_value(serde_json::Value::Object(fields))?;
    Ok(body)
  }
  let body = match multipart_body(multipart).await {
    Ok(body) => body,
    Err(e) => {
      return (axum::http::StatusCode::BAD_REQUEST, format!("Bad request: {e}")).into_response();
    }
  };
  let request = SubmitMetadataRequest { body };
  let result: anyhow::Result<ApiResponse<Metadata>> = service.submit_metadata(request).await;
  match result {
    Ok(ApiResponse::Ok(body)) => (http::StatusCode::OK, axum::Json(body)).into_response(),
    Ok(ApiResponse::Other(status, body)) => (status, body).into_response(),
    Err(e) => (
      axum::http::StatusCode::INTERNAL_SERVER_ERROR,
      format!("Internal error: {e}"),
    )
      .into_response(),
  }
}
pub async fn submit_counters<S>(State(service): State<S>, multipart: axum::extract::Multipart) -> impl IntoResponse
where
  S: ApiServer + Clone + Send + Sync + 'static,
{
  async fn multipart_body(mut multipart: axum::extract::Multipart) -> anyhow::Result<Counters> {
    let mut fields = serde_json::Map::new();
    let mut additional_properties_parts = serde_json::Map::new();
    while let Some(part) = multipart.next_field().await? {
      let Some(name) = part.name().map(str::to_owned) else {
        continue;
      };
      let value = serde_json::from_str(&part.text().await?)
        .map_err(|e| anyhow::anyhow!("invalid multipart part `{name}`: {e}"))?;
      if let serde_json::Value::Array(items) = additional_properties_parts
        .entry(name)
        .or_insert_with(|| serde_json::Value::Array(vec![]))
      {
        items.push(value);
      }
    }
    fields.extend(additional_properties_parts);
    let body: Counters = serde_json::from_value(serde_json::Value::Object(fields))?;
    Ok(body)
  }
  let body = match multipart_body(multipart).await {
    Ok(body) => body,
    Err(e) => {
      return (axum::http::StatusCode::BAD_REQUEST, format!("Bad request: {e}")).into_response();
    }
  };
  let request = SubmitCountersRequest { body };
  let result: anyhow::Result<ApiResponse<Counters>> = service.submit_counters(request).await;
  match result {
    Ok(ApiResponse::Ok(body)) => (http::StatusCode::OK, axum::Json(body)).into_response(),
    Ok(ApiResponse::Other(status, body)) => (status, body).into_response(),
    Err(e) => (
      axum::http::StatusCode::INTERNAL_SERVER_ERROR,
      format!("Internal error: {e}"),
    )
      .into_response(),
  }
}
pub fn router<S>(service: S) -> Router
where
  S: ApiServer + Clone + Send + Sync + 'static,
{
  Router::new()
    .route("/forms/{form_id}", post(submit_form::<S>))
    .route("/files", post(upload_files::<S>))
    .route("/metadata", post(submit_metadata::<S>))
    .route("/counters", post(submit_counters::<S>))
    .with_state(service)
}
