//!
//! AUTO-GENERATED CODE - DO NOT EDIT!
//!
//! Multipart Forms
//! Source: crates/oas3-gen/fixtures/multipart.json
//! Version: 1.0.0
//! Generated by `oas3-gen v0.29.0`
//!
//! Exercises multipart/form-data request bodies: file parts, Encoding Objects, and RFC 6570 styles

use anyhow::Context;
use reqwest::{Client, Url};
use validator::Validate;

use super::types::*;
pub const BASE_URL: &str = "http://localhost:8080";
#[derive(Debug, Clone)]
pub struct MultipartFormsClient {
  pub client: Client,
  pub base_url: Url,
}
impl Default for MultipartFormsClient {
  fn default() -> Self {
    Self::new()
  }
}
impl MultipartFormsClient {
  /// Create a client using the OpenAPI `servers[0]` URL.
  #[must_use]
  #[track_caller]
  pub fn new() -> Self {
    Self {
      client: Client::builder().build().expect("client"),
      base_url: Url::parse(BASE_URL).expect("valid base url"),
    }
  }
  /// Create a client with a custom base URL.
  pub fn with_base_url(base_url: impl AsRef<str>) -> anyhow::Result<Self> {
    Ok(Self {
      client: Client::builder().build().context("building reqwest client")?,
      base_url: Url::parse(base_url.as_ref()).context("parsing base url")?,
    })
  }
  /// Create a client from an existing `reqwest::Client`.
  pub fn with_client(base_url: impl AsRef<str>, client: Client) -> anyhow::Result<Self> {
    let url = Url::parse(base_url.as_ref()).context("parsing base url")?;
    Ok(Self { client, base_url: url })
  }
  /// Submit a form that mixes files, scalars, and structured values
  ///
  /// * Path: `POST /forms/{formId}`
  pub async fn submit_form(&self, request: SubmitFormRequest) -> anyhow::Result<ApiResponse<UploadForm>> {
    request.validate().context("parameter validation")?;
    let mut url = self.base_url.clone();
    url
      .path_segments_mut()
      .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
      .push("forms")
      .push(&request.path.form_id.clone());
    let mut req_builder = self.client.post(url);
    let body = request.body;
    let mut form = reqwest::multipart::Form::new().percent_encode_noop();
    form = form.text("name", body.name);
    if let Some(value) = body.file_name {
      form = form.text("fileName", value);
    }
    if let Some(value) = body.r#type {
      form = form.text("type", value);
    }
    if let Some(value) = body.resume {
      form = form.text("résumé", value);
    }
    if let Some(value) = body.file {
      form = form.part(
        "file",
        reqwest::multipart::Part::bytes(value)
          .file_name("file")
          .mime_str("application/octet-stream")?,
      );
    }
    for value in body.attachments {
      form = form.part(
        "attachments",
        reqwest::multipart::Part::bytes(value)
          .file_name("attachments")
          .mime_str("application/octet-stream")?,
      );
    }
    form = form.part(
      "thumbnail",
      reqwest::multipart::Part::bytes(body.thumbnail)
        .file_name("thumbnail")
        .mime_str("application/octet-stream")?,
    );
    if let serde_json::Value::String(text) = serde_json::to_value(serde_with::ser::SerializeAsWrap::<
      _,
      serde_with::base64::Base64,
    >::new(&body.encoded))?
    {
      form = form.text("encoded", text);
    }
    form = form.text("count", body.count.to_string());
    if let Some(value) = body.ratio {
      form = form.text("ratio", value.to_string());
    }
    if let Some(value) = body.enabled {
      form = form.text("enabled", value.to_string());
    }
    if let Some(value) = body.quality {
      form = form.text("quality", value.to_string());
    }
    if let Some(value) = body.level {
      form = form.text("level", value.to_string());
    }
    for value in body.tags.into_iter().flatten() {
      form = form.text("tags", value);
    }
    if let Some(value) = body.created_at
      && let serde_json::Value::String(text) = serde_json::to_value(value)?
    {
      form = form.text("createdAt", text);
    }
    if let Some(value) = body.address {
      form = form.part(
        "address",
        reqwest::multipart::Part::text(serde_json::to_string(&value)?).mime_str("application/json")?,
      );
    }
    for value in body.addresses.into_iter().flatten() {
      form = form.part(
        "addresses",
        reqwest::multipart::Part::text(serde_json::to_string(&value)?).mime_str("application/vnd.example+json")?,
      );
    }
    if let Some(value) = body.note {
      form = form.part("note", reqwest::multipart::Part::text(value).mime_str("text/markdown")?);
    }
    if let Some(value) = body.labels {
      match serde_json::to_value(value)? {
        serde_json::Value::Null => {}
        serde_json::Value::String(text) => {
          form = form.text("labels", text);
        }
        other => {
          form = form.part(
            "labels",
            reqwest::multipart::Part::text(other.to_string()).mime_str("application/json")?,
          );
        }
      }
    }
    let mut items = vec![];
    for value in body.ids.into_iter().flatten() {
      items.push(value.to_string());
    }
    if !items.is_empty() {
      form = form.text("ids", items.join("|"));
    }
    for value in body.colors.into_iter().flatten() {
      form = form.text("colors", value);
    }
    if let Some(value) = body.filter
      && let serde_json::Value::Object(members) = serde_json::to_value(value)?
    {
      for (key, member) in members {
        let text = match member {
          serde_json::Value::Null => continue,
          serde_json::Value::String(text) => text,
          other => other.to_string(),
        };
        form = form.text(format!("filter[{key}]"), text);
      }
    }
    if let Some(value) = body.range
      && let serde_json::Value::Object(members) = serde_json::to_value(value)?
    {
      let mut items = vec![];
      for (key, member) in members {
        let text = match member {
          serde_json::Value::Null => continue,
          serde_json::Value::String(text) => text,
          other => other.to_string(),
        };
        items.push(key);
        items.push(text);
      }
      if !items.is_empty() {
        form = form.text("range", items.join(","));
      }
    }
    if let Some(value) = body.extras
      && let serde_json::Value::Object(members) = serde_json::to_value(value)?
    {
      for (key, member) in members {
        let text = match member {
          serde_json::Value::Null => continue,
          serde_json::Value::String(text) => text,
          other => other.to_string(),
        };
        form = form.text(key, text);
      }
    }
    if let Some(value) = body.options
      && let serde_json::Value::Object(members) = serde_json::to_value(value)?
    {
      for (key, member) in members {
        let text = match member {
          serde_json::Value::Null => continue,
          serde_json::Value::String(text) => text,
          other => other.to_string(),
        };
        form = form.text(format!("options[{key}]"), text);
      }
    }
    req_builder = req_builder.multipart(form);
    let response = req_builder.send().await?;
    SubmitFormRequest::parse_response(response).await
  }
  /// Upload any number of files under one part name
  ///
  /// * Path: `POST /files`
  pub async fn upload_files(&self, request: UploadFilesRequest) -> anyhow::Result<ApiResponse<FilesReceipt>> {
    request.validate().context("parameter validation")?;
    let mut url = self.base_url.clone();
    url
      .path_segments_mut()
      .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
      .push("files");
    let mut req_builder = self.client.post(url);
    if let Some(body) = request.body {
      let has_parts =
        body.file.as_ref().is_some_and(|items| !items.is_empty()) || body.cover.is_some() || body.note.is_some();
      let mut form = reqwest::multipart::Form::new().percent_encode_noop();
      for value in body.file.into_iter().flatten() {
        form = form.part(
          "file",
          reqwest::multipart::Part::bytes(value)
            .file_name("file")
            .mime_str("application/octet-stream")?,
        );
      }
      if let Some(value) = body.cover {
        form = form.part(
          "cover",
          reqwest::multipart::Part::bytes(value)
            .file_name("cover")
            .mime_str("image/png")?,
        );
      }
      if let Some(value) = body.note {
        form = form.text("note", value);
      }
      req_builder = if has_parts {
        req_builder.multipart(form)
      } else {
        req_builder
          .header(
            http::header::CONTENT_TYPE,
            format!("multipart/form-data; boundary={}", form.boundary()),
          )
          .body(format!("--{}--\r\n", form.boundary()))
      };
    }
    let response = req_builder.send().await?;
    UploadFilesRequest::parse_response(response).await
  }
  /// Submit free-form text fields
  ///
  /// * Path: `POST /metadata`
  pub async fn submit_metadata(&self, request: SubmitMetadataRequest) -> anyhow::Result<ApiResponse<Metadata>> {
    request.validate().context("parameter validation")?;
    let mut url = self.base_url.clone();
    url
      .path_segments_mut()
      .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
      .push("metadata");
    let mut req_builder = self.client.post(url);
    let body = request.body;
    let has_parts = !body.additional_properties.is_empty();
    let mut form = reqwest::multipart::Form::new().percent_encode_noop();
    for (name, value) in body.additional_properties {
      form = form.text(name, value);
    }
    req_builder = if has_parts {
      req_builder.multipart(form)
    } else {
      req_builder
        .header(
          http::header::CONTENT_TYPE,
          format!("multipart/form-data; boundary={}", form.boundary()),
        )
        .body(format!("--{}--\r\n", form.boundary()))
    };
    let response = req_builder.send().await?;
    SubmitMetadataRequest::parse_response(response).await
  }
  /// Submit named lists of counts
  ///
  /// * Path: `POST /counters`
  pub async fn submit_counters(&self, request: SubmitCountersRequest) -> anyhow::Result<ApiResponse<Counters>> {
    request.validate().context("parameter validation")?;
    let mut url = self.base_url.clone();
    url
      .path_segments_mut()
      .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
      .push("counters");
    let mut req_builder = self.client.post(url);
    let body = request.body;
    let has_parts = body.additional_properties.values().any(|values| !values.is_empty());
    let mut form = reqwest::multipart::Form::new().percent_encode_noop();
    for (name, values) in body.additional_properties {
      for value in values {
        form = form.text(name.clone(), value.to_string());
      }
    }
    req_builder = if has_parts {
      req_builder.multipart(form)
    } else {
      req_builder
        .header(
          http::header::CONTENT_TYPE,
          format!("multipart/form-data; boundary={}", form.boundary()),
        )
        .body(format!("--{}--\r\n", form.boundary()))
    };
    let response = req_builder.send().await?;
    SubmitCountersRequest::parse_response(response).await
  }
}
