//!
//! AUTO-GENERATED CODE - DO NOT EDIT!
//!
//! Multipart Forms
//! Source: crates/oas3-gen/fixtures/multipart.json
//! Version: 1.0.0
//! Generated by `oas3-gen v0.29.0`
//!
//! Exercises multipart/form-data request bodies: file parts, Encoding Objects, and RFC 6570 styles

use serde::{Deserialize, Serialize};
use validator::Validate;
#[serde_with::serde_as]
#[serde_with::skip_serializing_none]
#[derive(
  Debug, Clone, PartialEq, Serialize, Deserialize, validator::Validate, oas3_gen_support::Default, bon::Builder,
)]
pub struct UploadForm {
  #[validate(length(min = 1u64))]
  pub name: String,
  #[serde(rename = "fileName")]
  pub file_name: Option<String>,
  #[serde(rename = "type")]
  pub r#type: Option<String>,
  /// A non-ASCII part name
  #[serde(rename = "résumé")]
  pub resume: Option<String>,
  /// A lexicon file
  pub file: Option<Vec<u8>>,
  pub attachments: Vec<Vec<u8>>,
  pub thumbnail: Vec<u8>,
  #[serde_as(as = "serde_with::base64::Base64")]
  pub encoded: Vec<u8>,
  pub count: i64,
  pub ratio: Option<f64>,
  pub enabled: Option<bool>,
  pub quality: Option<Quality>,
  pub level: Option<Level>,
  pub tags: Option<Vec<String>>,
  #[serde(rename = "createdAt")]
  pub created_at: Option<chrono::DateTime<chrono::Utc>>,
  #[validate(nested)]
  pub address: Option<Address>,
  #[validate(nested)]
  pub addresses: Option<Vec<Address>>,
  pub note: Option<String>,
  pub labels: Option<UploadFormLabels>,
  pub ids: Option<Vec<i64>>,
  pub colors: Option<Vec<String>>,
  pub filter: Option<Filter>,
  pub range: Option<Range>,
  pub extras: Option<Extras>,
  pub options: Option<indexmap::IndexMap<String, i64>>,
}
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize, oas3_gen_support::Default)]
pub enum Quality {
  #[serde(rename = "high")]
  #[default]
  High,
  #[serde(rename = "low")]
  Low,
}
impl core::fmt::Display for Quality {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    match self {
      Self::High => write!(f, "high"),
      Self::Low => write!(f, "low"),
    }
  }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash, oas3_gen_support::Default)]
pub enum Level {
  #[default]
  Value1,
  Value2,
  Value3,
}
impl core::fmt::Display for Level {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    match self {
      Self::Value1 => write!(f, "1"),
      Self::Value2 => write!(f, "2"),
      Self::Value3 => write!(f, "3"),
    }
  }
}
impl serde::Serialize for Level {
  fn serialize<S>(&self, serializer: S) -> core::result::Result<S::Ok, S::Error>
  where
    S: serde::Serializer,
  {
    let value: i64 = match self {
      Self::Value1 => 1i64,
      Self::Value2 => 2i64,
      Self::Value3 => 3i64,
    };
    serializer.serialize_i64(value)
  }
}
impl<'de> serde::Deserialize<'de> for Level {
  fn deserialize<D>(deserializer: D) -> core::result::Result<Self, D::Error>
  where
    D: serde::Deserializer<'de>,
  {
    let value = i64::deserialize(deserializer)?;
    match value {
      1i64 => Ok(Self::Value1),
      2i64 => Ok(Self::Value2),
      3i64 => Ok(Self::Value3),
      _ => Err(serde::de::Error::custom(format!(
        "unknown variant {}, expected one of: {}",
        value, "1, 2, 3"
      ))),
    }
  }
}
#[serde_with::skip_serializing_none]
#[derive(
  Debug, Clone, PartialEq, Serialize, Deserialize, validator::Validate, oas3_gen_support::Default, bon::Builder,
)]
pub struct Address {
  #[validate(length(min = 1u64))]
  pub city: String,
  pub zip: Option<String>,
}
#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default, bon::Builder)]
pub struct Filter {
  pub size: Option<i64>,
  pub color: Option<String>,
}
#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default, bon::Builder)]
pub struct Range {
  pub min: Option<i64>,
  pub max: Option<i64>,
}
#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default, bon::Builder)]
pub struct Extras {
  pub mood: Option<String>,
  pub score: Option<i64>,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default, bon::Builder)]
pub struct Metadata {
  /// Additional properties not defined in the schema.
  #[serde(flatten)]
  pub additional_properties: indexmap::IndexMap<String, String>,
}
#[derive(Debug, Clone, PartialEq, Deserialize, oas3_gen_support::Default, bon::Builder)]
pub struct FilesReceipt {
  pub sizes: Vec<i64>,
  pub note: Option<String>,
  #[serde(rename = "coverSize")]
  pub cover_size: Option<i64>,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default, bon::Builder)]
pub struct Counters {
  /// Additional properties not defined in the schema.
  #[serde(flatten)]
  pub additional_properties: indexmap::IndexMap<String, Vec<i64>>,
}
#[derive(Debug, Clone, PartialEq, validator::Validate, oas3_gen_support::Default)]
pub struct SubmitFormRequestPath {
  #[validate(length(min = 1u64))]
  pub form_id: String,
}
/// Submit a form that mixes files, scalars, and structured values
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub struct SubmitFormRequest {
  #[validate(nested)]
  pub path: SubmitFormRequestPath,
  #[validate(nested)]
  pub body: UploadForm,
}
#[bon::bon]
impl SubmitFormRequest {
  /// Create a new request with the given parameters.
  #[builder]
  pub fn new(form_id: String, body: UploadForm) -> anyhow::Result<Self> {
    let request = Self {
      path: SubmitFormRequestPath { form_id },
      body,
    };
    request.validate()?;
    Ok(request)
  }
}
impl SubmitFormRequest {
  /// Parse the HTTP response into the response enum.
  pub async fn parse_response(req: reqwest::Response) -> anyhow::Result<ApiResponse<UploadForm>> {
    let status = req.status();
    if status == http::StatusCode::OK {
      let data = oas3_gen_support::Diagnostics::<UploadForm>::json_with_diagnostics(req).await?;
      return Ok(ApiResponse::Ok(data));
    }
    Ok(ApiResponse::Other(status, req.bytes().await?.to_vec()))
  }
}
#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, PartialEq, Serialize, oas3_gen_support::Default, bon::Builder)]
pub struct FileRequestBody {
  pub file: Option<Vec<Vec<u8>>>,
  /// Raw binary: the schema declares no type
  pub cover: Option<Vec<u8>>,
  pub note: Option<String>,
}
/// Upload any number of files under one part name
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub struct UploadFilesRequest {
  pub body: Option<FileRequestBody>,
}
#[bon::bon]
impl UploadFilesRequest {
  /// Create a new request with the given parameters.
  #[builder]
  pub fn new(body: Option<FileRequestBody>) -> anyhow::Result<Self> {
    let request = Self { body };
    request.validate()?;
    Ok(request)
  }
}
impl UploadFilesRequest {
  /// Parse the HTTP response into the response enum.
  pub async fn parse_response(req: reqwest::Response) -> anyhow::Result<ApiResponse<FilesReceipt>> {
    let status = req.status();
    if status == http::StatusCode::OK {
      let data = oas3_gen_support::Diagnostics::<FilesReceipt>::json_with_diagnostics(req).await?;
      return Ok(ApiResponse::Ok(data));
    }
    Ok(ApiResponse::Other(status, req.bytes().await?.to_vec()))
  }
}
/// Submit free-form text fields
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub struct SubmitMetadataRequest {
  pub body: Metadata,
}
#[bon::bon]
impl SubmitMetadataRequest {
  /// Create a new request with the given parameters.
  #[builder]
  pub fn new(body: Metadata) -> anyhow::Result<Self> {
    let request = Self { body };
    request.validate()?;
    Ok(request)
  }
}
impl SubmitMetadataRequest {
  /// Parse the HTTP response into the response enum.
  pub async fn parse_response(req: reqwest::Response) -> anyhow::Result<ApiResponse<Metadata>> {
    let status = req.status();
    if status == http::StatusCode::OK {
      let data = oas3_gen_support::Diagnostics::<Metadata>::json_with_diagnostics(req).await?;
      return Ok(ApiResponse::Ok(data));
    }
    Ok(ApiResponse::Other(status, req.bytes().await?.to_vec()))
  }
}
/// Submit named lists of counts
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub struct SubmitCountersRequest {
  pub body: Counters,
}
#[bon::bon]
impl SubmitCountersRequest {
  /// Create a new request with the given parameters.
  #[builder]
  pub fn new(body: Counters) -> anyhow::Result<Self> {
    let request = Self { body };
    request.validate()?;
    Ok(request)
  }
}
impl SubmitCountersRequest {
  /// Parse the HTTP response into the response enum.
  pub async fn parse_response(req: reqwest::Response) -> anyhow::Result<ApiResponse<Counters>> {
    let status = req.status();
    if status == http::StatusCode::OK {
      let data = oas3_gen_support::Diagnostics::<Counters>::json_with_diagnostics(req).await?;
      return Ok(ApiResponse::Ok(data));
    }
    Ok(ApiResponse::Other(status, req.bytes().await?.to_vec()))
  }
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UploadFormLabels {
  Object(indexmap::IndexMap<String, String>),
  String(String),
}
/// Response enum shared by every operation.
///
/// `Value` is the operation's success body type and `Failure` its error body type.
/// A status code is a unit variant when no operation gives it a body.
#[derive(Debug, Clone)]
pub enum ApiResponse<Value> {
  ///200
  Ok(Value),
  ///Status code the operation does not declare; carries the raw body.
  Other(http::StatusCode, Vec<u8>),
}
