//!
//! AUTO-GENERATED CODE - DO NOT EDIT!
//!
//! Key Vault
//! Source: crates/oas3-gen/fixtures/api_key_security.json
//! Version: 1.0.0
//! Generated by `oas3-gen v0.29.0`
//!
//! Exercises apiKey security schemes in headers, query strings, and cookies.

use axum::{
  Router,
  extract::{Path, Query, State},
  response::IntoResponse,
  routing::get,
};

use super::types::*;
pub trait ApiServer: Send + Sync {
  /// List secrets with the global header key
  ///
  /// * Path: `GET /secrets`
  fn list_secrets(
    &self,
    request: ListSecretsRequest,
  ) -> impl std::future::Future<Output = anyhow::Result<ApiResponse<Secret200Response, Error>>> + Send;
  /// Create a secret with a query key or a session cookie
  ///
  /// * Path: `POST /secrets`
  fn create_secret(
    &self,
    request: CreateSecretRequest,
  ) -> impl std::future::Future<Output = anyhow::Result<ApiResponse<Secret, Error>>> + Send;
  /// Read a secret with both the header key and a session cookie
  ///
  /// * Path: `GET /secrets/{secretId}`
  fn get_secret(
    &self,
    request: GetSecretRequest,
  ) -> impl std::future::Future<Output = anyhow::Result<ApiResponse<Secret, Error>>> + Send;
  /// Delete a secret with a bearer token or the header key
  ///
  /// * Path: `DELETE /secrets/{secretId}`
  fn delete_secret(
    &self,
    request: DeleteSecretRequest,
  ) -> impl std::future::Future<Output = anyhow::Result<ApiResponse<(), Error>>> + Send;
  /// Report health without credentials
  ///
  /// * Path: `GET /health`
  fn get_health(
    &self,
    request: GetHealthRequest,
  ) -> impl std::future::Future<Output = anyhow::Result<ApiResponse<(), ()>>> + Send;
}
impl ApiKeyAuthCredentials {
  fn from_parts(parts: &axum::http::request::Parts) -> Result<Self, (axum::http::StatusCode, &'static str)> {
    Ok(Self {
      api_key_auth: parts
        .headers
        .get(X_API_KEY)
        .and_then(|value| value.to_str().ok())
        .map(secrecy::SecretString::from)
        .ok_or((
          axum::http::StatusCode::UNAUTHORIZED,
          "missing API key in the `X-Api-Key` header",
        ))?,
    })
  }
}
impl<S: Send + Sync> axum::extract::FromRequestParts<S> for ApiKeyAuthCredentials {
  type Rejection = (axum::http::StatusCode, &'static str);
  fn from_request_parts(
    parts: &mut axum::http::request::Parts,
    _state: &S,
  ) -> impl std::future::Future<Output = Result<Self, Self::Rejection>> + Send {
    std::future::ready(Self::from_parts(parts))
  }
}
impl QueryKeyAndSessionCookieCredentials {
  fn from_parts(parts: &axum::http::request::Parts) -> Result<Self, (axum::http::StatusCode, &'static str)> {
    let Query(query) = Query::<Vec<(String, String)>>::try_from_uri(&parts.uri).unwrap_or_default();
    let cookies = axum_extra::extract::CookieJar::from_headers(&parts.headers);
    let credentials = Self {
      query_key: query
        .iter()
        .find(|(name, _)| name == "api_key")
        .map(|(_, value)| secrecy::SecretString::from(value.as_str())),
      session_cookie: cookies
        .get("session")
        .map(|cookie| secrecy::SecretString::from(cookie.value_trimmed())),
    };
    if !(credentials.query_key.is_some() || credentials.session_cookie.is_some()) {
      return Err((
        axum::http::StatusCode::UNAUTHORIZED,
        "missing credentials for `QueryKey` or `SessionCookie`",
      ));
    }
    Ok(credentials)
  }
}
impl<S: Send + Sync> axum::extract::FromRequestParts<S> for QueryKeyAndSessionCookieCredentials {
  type Rejection = (axum::http::StatusCode, &'static str);
  fn from_request_parts(
    parts: &mut axum::http::request::Parts,
    _state: &S,
  ) -> impl std::future::Future<Output = Result<Self, Self::Rejection>> + Send {
    std::future::ready(Self::from_parts(parts))
  }
}
impl ApiKeyAuthAndSessionCookieCredentials {
  fn from_parts(parts: &axum::http::request::Parts) -> Result<Self, (axum::http::StatusCode, &'static str)> {
    let cookies = axum_extra::extract::CookieJar::from_headers(&parts.headers);
    Ok(Self {
      api_key_auth: parts
        .headers
        .get(X_API_KEY)
        .and_then(|value| value.to_str().ok())
        .map(secrecy::SecretString::from)
        .ok_or((
          axum::http::StatusCode::UNAUTHORIZED,
          "missing API key in the `X-Api-Key` header",
        ))?,
      session_cookie: cookies
        .get("session")
        .map(|cookie| secrecy::SecretString::from(cookie.value_trimmed()))
        .ok_or((
          axum::http::StatusCode::UNAUTHORIZED,
          "missing API key in the `session` cookie",
        ))?,
    })
  }
}
impl<S: Send + Sync> axum::extract::FromRequestParts<S> for ApiKeyAuthAndSessionCookieCredentials {
  type Rejection = (axum::http::StatusCode, &'static str);
  fn from_request_parts(
    parts: &mut axum::http::request::Parts,
    _state: &S,
  ) -> impl std::future::Future<Output = Result<Self, Self::Rejection>> + Send {
    std::future::ready(Self::from_parts(parts))
  }
}
impl ApiKeyAuthCredentials2 {
  fn from_parts(parts: &axum::http::request::Parts) -> Result<Self, (axum::http::StatusCode, &'static str)> {
    Ok(Self {
      api_key_auth: parts
        .headers
        .get(X_API_KEY)
        .and_then(|value| value.to_str().ok())
        .map(secrecy::SecretString::from),
    })
  }
}
impl<S: Send + Sync> axum::extract::FromRequestParts<S> for ApiKeyAuthCredentials2 {
  type Rejection = (axum::http::StatusCode, &'static str);
  fn from_request_parts(
    parts: &mut axum::http::request::Parts,
    _state: &S,
  ) -> impl std::future::Future<Output = Result<Self, Self::Rejection>> + Send {
    std::future::ready(Self::from_parts(parts))
  }
}
pub async fn list_secrets<S>(
  State(service): State<S>,
  credentials: ApiKeyAuthCredentials,
  Query(query): Query<ListSecretsRequestQuery>,
) -> impl IntoResponse
where
  S: ApiServer + Clone + Send + Sync + 'static,
{
  let request = ListSecretsRequest { query, credentials };
  let result: anyhow::Result<ApiResponse<Secret200Response, Error>> = service.list_secrets(request).await;
  match result {
    Ok(ApiResponse::Ok(body)) => (http::StatusCode::OK, axum::Json(body)).into_response(),
    Ok(ApiResponse::Created(body)) => (http::StatusCode::CREATED, axum::Json(body)).into_response(),
    Ok(ApiResponse::NoContent) => http::StatusCode::NO_CONTENT.into_response(),
    Ok(ApiResponse::Unauthorized(body)) => (http::StatusCode::UNAUTHORIZED, axum::Json(body)).into_response(),
    Ok(ApiResponse::Other(status, body)) => (status, body).into_response(),
    Err(e) => (
      axum::http::StatusCode::INTERNAL_SERVER_ERROR,
      format!("Internal error: {e}"),
    )
      .into_response(),
  }
}
pub async fn create_secret<S>(
  State(service): State<S>,
  credentials: QueryKeyAndSessionCookieCredentials,
  axum::Json(body): axum::Json<NewSecret>,
) -> impl IntoResponse
where
  S: ApiServer + Clone + Send + Sync + 'static,
{
  let request = CreateSecretRequest { credentials, body };
  let result: anyhow::Result<ApiResponse<Secret, Error>> = service.create_secret(request).await;
  match result {
    Ok(ApiResponse::Ok(body)) => (http::StatusCode::OK, axum::Json(body)).into_response(),
    Ok(ApiResponse::Created(body)) => (http::StatusCode::CREATED, axum::Json(body)).into_response(),
    Ok(ApiResponse::NoContent) => http::StatusCode::NO_CONTENT.into_response(),
    Ok(ApiResponse::Unauthorized(body)) => (http::StatusCode::UNAUTHORIZED, axum::Json(body)).into_response(),
    Ok(ApiResponse::Other(status, body)) => (status, body).into_response(),
    Err(e) => (
      axum::http::StatusCode::INTERNAL_SERVER_ERROR,
      format!("Internal error: {e}"),
    )
      .into_response(),
  }
}
pub async fn get_secret<S>(
  State(service): State<S>,
  credentials: ApiKeyAuthAndSessionCookieCredentials,
  Path(path): Path<GetSecretRequestPath>,
) -> impl IntoResponse
where
  S: ApiServer + Clone + Send + Sync + 'static,
{
  let request = GetSecretRequest { path, credentials };
  let result: anyhow::Result<ApiResponse<Secret, Error>> = service.get_secret(request).await;
  match result {
    Ok(ApiResponse::Ok(body)) => (http::StatusCode::OK, axum::Json(body)).into_response(),
    Ok(ApiResponse::Created(body)) => (http::StatusCode::CREATED, axum::Json(body)).into_response(),
    Ok(ApiResponse::NoContent) => http::StatusCode::NO_CONTENT.into_response(),
    Ok(ApiResponse::Unauthorized(body)) => (http::StatusCode::UNAUTHORIZED, axum::Json(body)).into_response(),
    Ok(ApiResponse::Other(status, body)) => (status, body).into_response(),
    Err(e) => (
      axum::http::StatusCode::INTERNAL_SERVER_ERROR,
      format!("Internal error: {e}"),
    )
      .into_response(),
  }
}
pub async fn delete_secret<S>(
  State(service): State<S>,
  credentials: ApiKeyAuthCredentials2,
  Path(path): Path<DeleteSecretRequestPath>,
) -> impl IntoResponse
where
  S: ApiServer + Clone + Send + Sync + 'static,
{
  let request = DeleteSecretRequest { path, credentials };
  let result: anyhow::Result<ApiResponse<(), Error>> = service.delete_secret(request).await;
  match result {
    Ok(ApiResponse::Ok(())) => http::StatusCode::OK.into_response(),
    Ok(ApiResponse::Created(())) => http::StatusCode::CREATED.into_response(),
    Ok(ApiResponse::NoContent) => http::StatusCode::NO_CONTENT.into_response(),
    Ok(ApiResponse::Unauthorized(body)) => (http::StatusCode::UNAUTHORIZED, axum::Json(body)).into_response(),
    Ok(ApiResponse::Other(status, body)) => (status, body).into_response(),
    Err(e) => (
      axum::http::StatusCode::INTERNAL_SERVER_ERROR,
      format!("Internal error: {e}"),
    )
      .into_response(),
  }
}
pub async fn get_health<S>(State(service): State<S>) -> impl IntoResponse
where
  S: ApiServer + Clone + Send + Sync + 'static,
{
  let request = GetHealthRequest {};
  let result: anyhow::Result<ApiResponse<(), ()>> = service.get_health(request).await;
  match result {
    Ok(ApiResponse::Ok(())) => http::StatusCode::OK.into_response(),
    Ok(ApiResponse::Created(())) => http::StatusCode::CREATED.into_response(),
    Ok(ApiResponse::NoContent) => http::StatusCode::NO_CONTENT.into_response(),
    Ok(ApiResponse::Unauthorized(())) => http::StatusCode::UNAUTHORIZED.into_response(),
    Ok(ApiResponse::Other(status, body)) => (status, body).into_response(),
    Err(e) => (
      axum::http::StatusCode::INTERNAL_SERVER_ERROR,
      format!("Internal error: {e}"),
    )
      .into_response(),
  }
}
pub fn router<S>(service: S) -> Router
where
  S: ApiServer + Clone + Send + Sync + 'static,
{
  Router::new()
    .route("/secrets", get(list_secrets::<S>).post(create_secret::<S>))
    .route("/secrets/{secret_id}", get(get_secret::<S>).delete(delete_secret::<S>))
    .route("/health", get(get_health::<S>))
    .with_state(service)
}
