//!
//! AUTO-GENERATED CODE - DO NOT EDIT!
//!
//! Key Vault
//! Source: crates/oas3-gen/fixtures/api_key_security.json
//! Version: 1.0.0
//! Generated by `oas3-gen v0.29.0`
//!
//! Exercises apiKey security schemes in headers, query strings, and cookies.

use serde::{Deserialize, Serialize};
use validator::Validate;
pub const X_API_KEY: http::HeaderName = http::HeaderName::from_static("x-api-key");
#[derive(Debug, Clone, PartialEq, Serialize, oas3_gen_support::Default, bon::Builder)]
pub struct Secret {
  pub id: String,
  pub name: String,
}
#[derive(Debug, Clone, PartialEq, Deserialize, validator::Validate, oas3_gen_support::Default, bon::Builder)]
pub struct NewSecret {
  #[validate(length(min = 1u64))]
  pub name: String,
  #[validate(length(min = 1u64))]
  pub value: String,
}
#[derive(Debug, Clone, PartialEq, Serialize, oas3_gen_support::Default, bon::Builder)]
pub struct Error {
  pub code: String,
  pub message: String,
}
#[derive(Debug, Clone, PartialEq, Deserialize, validator::Validate, oas3_gen_support::Default)]
pub struct ListSecretsRequestQuery {
  #[validate(range(min = 1i64))]
  pub limit: Option<i64>,
}
/// List secrets with the global header key
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub struct ListSecretsRequest {
  #[validate(nested)]
  pub query: ListSecretsRequestQuery,
  pub credentials: ApiKeyAuthCredentials,
}
#[bon::bon]
impl ListSecretsRequest {
  /// Create a new request with the given parameters.
  #[builder]
  pub fn new(limit: Option<i64>, credentials: ApiKeyAuthCredentials) -> anyhow::Result<Self> {
    let request = Self {
      query: ListSecretsRequestQuery { limit },
      credentials,
    };
    request.validate()?;
    Ok(request)
  }
}
/// Create a secret with a query key or a session cookie
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub struct CreateSecretRequest {
  pub credentials: QueryKeyAndSessionCookieCredentials,
  #[validate(nested)]
  pub body: NewSecret,
}
#[bon::bon]
impl CreateSecretRequest {
  /// Create a new request with the given parameters.
  #[builder]
  pub fn new(credentials: QueryKeyAndSessionCookieCredentials, body: NewSecret) -> anyhow::Result<Self> {
    let request = Self { credentials, body };
    request.validate()?;
    Ok(request)
  }
}
#[derive(Debug, Clone, PartialEq, Deserialize, validator::Validate, oas3_gen_support::Default)]
pub struct GetSecretRequestPath {
  #[validate(length(min = 1u64))]
  pub secret_id: String,
}
/// Read a secret with both the header key and a session cookie
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub struct GetSecretRequest {
  #[validate(nested)]
  pub path: GetSecretRequestPath,
  pub credentials: ApiKeyAuthAndSessionCookieCredentials,
}
#[bon::bon]
impl GetSecretRequest {
  /// Create a new request with the given parameters.
  #[builder]
  pub fn new(secret_id: String, credentials: ApiKeyAuthAndSessionCookieCredentials) -> anyhow::Result<Self> {
    let request = Self {
      path: GetSecretRequestPath { secret_id },
      credentials,
    };
    request.validate()?;
    Ok(request)
  }
}
#[derive(Debug, Clone, PartialEq, Deserialize, validator::Validate, oas3_gen_support::Default)]
pub struct DeleteSecretRequestPath {
  #[validate(length(min = 1u64))]
  pub secret_id: String,
}
/// Delete a secret with a bearer token or the header key
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub struct DeleteSecretRequest {
  #[validate(nested)]
  pub path: DeleteSecretRequestPath,
  pub credentials: ApiKeyAuthCredentials2,
}
#[bon::bon]
impl DeleteSecretRequest {
  /// Create a new request with the given parameters.
  #[builder]
  pub fn new(secret_id: String, credentials: ApiKeyAuthCredentials2) -> anyhow::Result<Self> {
    let request = Self {
      path: DeleteSecretRequestPath { secret_id },
      credentials,
    };
    request.validate()?;
    Ok(request)
  }
}
/// Report health without credentials
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub struct GetHealthRequest {}
/// API keys an operation accepts, read from the request before the operation runs.
#[derive(Debug, Clone, oas3_gen_support::Default)]
pub struct ApiKeyAuthCredentials {
  /// Key issued in the vault dashboard.
  ///
  /// `ApiKeyAuth` API key, read from the `X-Api-Key` header.
  pub api_key_auth: secrecy::SecretString,
}
/// API keys an operation accepts, read from the request before the operation runs.
#[derive(Debug, Clone, oas3_gen_support::Default)]
pub struct QueryKeyAndSessionCookieCredentials {
  /// `QueryKey` API key, read from the `api_key` query parameter.
  pub query_key: Option<secrecy::SecretString>,
  /// `SessionCookie` API key, read from the `session` cookie.
  pub session_cookie: Option<secrecy::SecretString>,
}
/// API keys an operation accepts, read from the request before the operation runs.
#[derive(Debug, Clone, oas3_gen_support::Default)]
pub struct ApiKeyAuthAndSessionCookieCredentials {
  /// Key issued in the vault dashboard.
  ///
  /// `ApiKeyAuth` API key, read from the `X-Api-Key` header.
  pub api_key_auth: secrecy::SecretString,
  /// `SessionCookie` API key, read from the `session` cookie.
  pub session_cookie: secrecy::SecretString,
}
/// API keys an operation accepts, read from the request before the operation runs.
#[derive(Debug, Clone, oas3_gen_support::Default)]
pub struct ApiKeyAuthCredentials2 {
  /// Key issued in the vault dashboard.
  ///
  /// `ApiKeyAuth` API key, read from the `X-Api-Key` header.
  pub api_key_auth: Option<secrecy::SecretString>,
}
pub type Secret200Response = Vec<Secret>;
/// Response enum shared by every operation.
///
/// `Value` is the operation's success body type and `Failure` its error body type.
/// A status code is a unit variant when no operation gives it a body.
#[derive(Debug, Clone)]
pub enum ApiResponse<Value, Failure> {
  ///200
  Ok(Value),
  ///201
  Created(Value),
  ///204
  NoContent,
  ///401
  Unauthorized(Failure),
  ///Status code the operation does not declare; carries the raw body.
  Other(http::StatusCode, Vec<u8>),
}
