//!
//! AUTO-GENERATED CODE - DO NOT EDIT!
//!
//! Intersection Union Test
//! Source: crates/oas3-gen/fixtures/intersection_union.json
//! Version: 1.0.0
//! Generated by `oas3-gen v0.24.1`
//!
//! No description provided

use serde::{Deserialize, Serialize};
///Must be a vehicle with an ID, and must be either a Car or a Boat.
#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, validator::Validate, oas3_gen_support::Default)]
pub struct Vehicle {
  #[validate(length(min = 1u64))]
  pub id: String,
  pub sails: Option<i64>,
  pub wheels: Option<i64>,
}
